import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home,LayoutDashboard,Target,ShoppingCart,Calculator,Link as LinkIcon,Settings,Plus,X,WalletCards,House,Search,Trash2,ExternalLink} from 'lucide-react';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
type Item={id:string;nome:string;categoria:string;quantidade:number;unidade:string;prioridade:string;status:string;valor_estimado:number|null;valor_minimo:number|null;valor_maximo:number|null;valor_pago:number|null;links:{titulo:string;url:string;preco:number|null}[];forma_pagamento?:string|null};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function App(){
 const [items,setItems]=useState<Item[]>([]),[open,setOpen]=useState(false),[search,setSearch]=useState(''),[filter,setFilter]=useState('TODOS');
 const load=()=>fetch(`${API}/api/items`).then(r=>r.json()).then(setItems).catch(()=>{}); useEffect(load,[]);
 const invested=useMemo(()=>items.reduce((s,i)=>s+Number(i.valor_pago||0),0),[items]); const done=items.filter(i=>i.status==='COMPRADO').length;
 const expected=items.reduce((s,i)=>s+Number(i.valor_estimado||0),0); const visible=items.filter(i=>(filter==='TODOS'||i.prioridade===filter)&&i.nome.toLowerCase().includes(search.toLowerCase()));
 return <div className="app"><aside><div className="brand"><House/><b>Plano de<br/>Independência</b></div><nav>{[[LayoutDashboard,'Dashboard'],[WalletCards,'Renda e Orçamento'],[Target,'Metas'],[Home,'Itens da Casa'],[ShoppingCart,'Plano de Compras'],[Calculator,'Simulador'],[LinkIcon,'Links']].map(([I,t]:any)=><button className={t==='Dashboard'?'active':''}><I size={19}/>{t}</button>)}</nav><div className="asideBottom"><Settings size={18}/> Configurações</div></aside>
 <main><header><div><h1>Plano para sair de casa</h1><p>Organizando hoje o nosso próximo espaço.</p></div><div className="date">📅 <small>Data da mudança (meta)</small><b>Junho / 2027</b></div></header>
 <section className="kpis"><Kpi icon="💰" title="Dinheiro guardado" value="R$ 0,00" sub="Reserva para a mudança"/><Kpi icon="🏠" title="Já investido na casa" value={money(invested)} sub={`${done} de ${items.length} itens comprados`}/><Kpi icon="🎯" title="Custo estimado" value={money(expected)} sub="Itens cadastrados"/><Kpi icon="🍽️" title="Cartão alimentação" value="R$ 600" sub="por mês"/></section>
 <section className="rooms">{['Cozinha','Sala','Quarto','Banheiro','Lavanderia','Geral'].map(c=>{let a=items.filter(i=>i.categoria===c),d=a.filter(i=>i.status==='COMPRADO').length;return <div className="room"><span>{c==='Cozinha'?'🍳':c==='Sala'?'🛋️':c==='Quarto'?'🛏️':c==='Banheiro'?'🚿':c==='Lavanderia'?'🧺':'📦'}</span><b>{c}</b><small>{d} de {a.length}</small><div className="bar"><i style={{width:`${a.length?d/a.length*100:0}%`}}/></div></div>})}</section>
 <section className="panel"><div className="panelTop"><div><h2>Itens da casa</h2><div className="filters">{['TODOS','ESSENCIAL','ALTA','MEDIA','BAIXA'].map(f=><button onClick={()=>setFilter(f)} className={filter===f?'selected':''}>{f==='TODOS'?`Todos (${items.length})`:f[0]+f.slice(1).toLowerCase()}</button>)}</div></div><div className="actions"><label><Search size={16}/><input placeholder="Buscar item..." value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="primary" onClick={()=>setOpen(true)}><Plus size={17}/> Adicionar item</button></div></div>
 <div className="table"><div className="tr th"><span>Item</span><span>Categoria</span><span>Qtd</span><span>Prioridade</span><span>Status</span><span>Valor (est.)</span><span>Pago</span><span>Links</span></div>{visible.map(i=><div className="tr"><strong>{i.nome}</strong><span>{i.categoria}</span><span>{i.quantidade} {i.unidade}</span><span><em className={'pill '+i.prioridade.toLowerCase()}>{i.prioridade}</em></span><span><em className={'pill '+i.status.toLowerCase()}>{i.status==='PENDENTE'?'Comprar':i.status==='COMPRADO'?'Feito':'Em execução'}</em></span><span>{i.valor_estimado?money(Number(i.valor_estimado)):'—'}</span><span className="paid">{i.valor_pago?money(Number(i.valor_pago)):'—'}</span><span>{i.links.length? <a href={i.links[0].url} target="_blank"><ExternalLink size={15}/> {i.links.length}</a>:'—'}</span></div>)}</div></section>
 <section className="bottom"><div className="panel"><h2>Links rápidos</h2><div className="quick"><a href="https://www.amazon.com.br" target="_blank">Amazon</a><a href="https://www.mercadolivre.com.br" target="_blank">Mercado Livre</a><a href="https://www.magazineluiza.com.br" target="_blank">Magazine Luiza</a><a href="https://www.kabum.com.br" target="_blank">KaBuM!</a></div></div><div className="panel"><h2>Resumo</h2><p className="summary"><b>{money(invested)}</b> já investidos em itens da casa.</p></div></section>
 </main>{open&&<AddModal close={()=>setOpen(false)} saved={()=>{setOpen(false);load()}}/>}</div>
}
function Kpi({icon,title,value,sub}:any){return <div className="kpi"><span>{icon}</span><div><small>{title}</small><h2>{value}</h2><p>{sub}</p></div></div>}
function AddModal({close,saved}:any){const [form,setForm]=useState<any>({nome:'',categoria:'Cozinha',quantidade:1,unidade:'un.',prioridade:'ESSENCIAL',status:'PENDENTE',valor_minimo:'',valor_estimado:'',valor_maximo:'',valor_pago:'',forma_pagamento:'',observacao:'',links:[{titulo:'Produto',url:'',preco:''}]}); const set=(k:string,v:any)=>setForm({...form,[k]:v}); const submit=async()=>{let body={...form};['valor_minimo','valor_estimado','valor_maximo','valor_pago'].forEach(k=>body[k]=body[k]?Number(body[k]):null); body.links=body.links.filter((l:any)=>l.url).map((l:any)=>({...l,preco:l.preco?Number(l.preco):null})); let r=await fetch(`${API}/api/items`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}); if(r.ok)saved(); else alert('Não foi possível salvar o item.');}; return <div className="drawer"><div className="drawerHead"><h2>Adicionar item</h2><button onClick={close}><X/></button></div><Field label="Nome do item *"><input placeholder="Ex.: Geladeira" value={form.nome} onChange={e=>set('nome',e.target.value)}/></Field><Field label="Categoria *"><select value={form.categoria} onChange={e=>set('categoria',e.target.value)}>{['Cozinha','Sala','Quarto','Banheiro','Lavanderia','Geral'].map(x=><option>{x}</option>)}</select></Field><div className="two"><Field label="Quantidade"><input type="number" value={form.quantidade} onChange={e=>set('quantidade',+e.target.value)}/></Field><Field label="Prioridade"><select value={form.prioridade} onChange={e=>set('prioridade',e.target.value)}>{['ESSENCIAL','ALTA','MEDIA','BAIXA'].map(x=><option>{x}</option>)}</select></Field></div><Field label="Status"><select value={form.status} onChange={e=>set('status',e.target.value)}><option value="PENDENTE">Comprar</option><option value="EM_EXECUCAO">Em execução</option><option value="COMPRADO">Feito</option></select></Field><label className="label">Preços (R$)</label><div className="three">{[['valor_minimo','Mínimo'],['valor_estimado','Estimado'],['valor_maximo','Máximo']].map(([k,p])=><input type="number" placeholder={p} value={form[k]} onChange={e=>set(k,e.target.value)}/>)}</div><Field label="Valor pago"><input type="number" placeholder="0,00" value={form.valor_pago} onChange={e=>set('valor_pago',e.target.value)}/></Field><Field label="Link do produto"><input placeholder="https://..." value={form.links[0].url} onChange={e=>set('links',[{...form.links[0],url:e.target.value}])}/></Field><Field label="Forma de pagamento"><select value={form.forma_pagamento} onChange={e=>set('forma_pagamento',e.target.value)}><option value="">Selecione</option><option>Dinheiro / PIX</option><option>Cartão alimentação</option><option>Cartão de crédito</option></select></Field><Field label="Observação"><textarea value={form.observacao} onChange={e=>set('observacao',e.target.value)}/></Field><div className="drawerActions"><button onClick={close}>Cancelar</button><button className="primary" onClick={submit}>Salvar item</button></div></div>}
function Field({label,children}:any){return <label className="field"><span>{label}</span>{children}</label>}
createRoot(document.getElementById('root')!).render(<App/>);
